{
 "title": "ADDS",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Subscriptions",
    "label": "Subscriptions",
    "query": {}
   },
   {
    "name": "Workspaces",
    "label": "Workspaces",
    "query": {}
   },
   {
    "name": "PerformanceCounters",
    "label": "Perf Counters",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 16, "x": 0, "y": 0 },
   "options": {
    "content": "# Active Directory Services (ADDS)\n\nAzure Monitoring Packs"
   }
  },
  {
   "title": "% Processor Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 3 },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": true,
      "query": "Perf\r\n| where CounterName == '% Processor Time'\r\n| summarize by Computer, TimeGenerated, CounterValue",
      "resources": [ "$Workspaces" ],
      "resultFormat": "logs",
      "timeColumn": "TimeGenerated"
     }
    }
   ]
  },
  {
   "title": "Available Bytes",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 3 },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": true,
      "query": "Perf\r\n| where CounterName == 'Available Bytes'\r\n| summarize by Computer, TimeGenerated, CounterValue",
      "resources": [ "$Workspaces" ],
      "resultFormat": "logs",
      "timeColumn": "TimeGenerated"
     }
    }
   ]
  },
  {
   "title": "LDAP Client Sessions",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 9 },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": true,
      "query": "Perf\r\n| where CounterName == 'LDAP Client Sessions'\r\n| summarize by Computer, TimeGenerated, CounterValue",
      "resources": [ "$Workspaces" ],
      "resultFormat": "logs",
      "timeColumn": "TimeGenerated"
     }
    }
   ]
  },
  {
   "title": "DNS Queries received/sec",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 9 },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": true,
      "query": "Perf\r\n| where CounterName == 'Total Query Received/sec'\r\n| summarize by Computer, TimeGenerated, CounterValue",
      "resources": [ "$Workspaces" ],
      "resultFormat": "logs",
      "timeColumn": "TimeGenerated"
     }
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 16, "x": 0, "y": 16 }, "options": { "content": "# Custom Metrics" } },
  {
   "title": "ADDS LSASS CPU Pct",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 18 },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": true,
      "query": "addsmonitoring_CL\r\n| parse RawData with TimeIngested \",\" Metric \",\" Value \",\" remainder\r\n| where Metric =~ 'ADDSlsassCPU'\r\n| project TimeGenerated, Value=toint(Value)",
      "resources": [ "$Workspaces" ],
      "resultFormat": "logs",
      "timeColumn": "TimeGenerated"
     }
    }
   ]
  },
  {
   "title": "AD Log File Drive Disk Space Pct Used",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 18 },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": true,
      "query": "addsmonitoring_CL\r\n| parse RawData with TimeIngested \",\" Metric \",\" Value \",\" remainder\r\n| where Metric =~ 'ADLogFileDriveDiskSpacePctUsed'\r\n| project TimeGenerated, Value=todouble(Value)",
      "resources": [ "$Workspaces" ],
      "resultFormat": "logs",
      "timeColumn": "TimeGenerated"
     }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 16, "x": 0, "y": 25 },
   "options": {
    "content": "# Pick a Counter: \"${PerformanceCounters}\"\r\n\r\nSelect a Counter at the top of the dashboard"
   }
  },
  {
   "title": "$PerformanceCounters",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 28 },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": true,
      "query": "Perf\r\n| where CounterName == '$PerformanceCounters'\r\n| summarize by Computer, TimeGenerated, CounterValue",
      "resources": [ "$Workspaces" ],
      "resultFormat": "logs",
      "timeColumn": "TimeGenerated"
     }
    }
   ]
  }
 ]
}